"""initial schema

Revision ID: 2bf4c67cb1b1
Revises: 
Create Date: 2026-09-26 18:33:34.713571

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '2bf4c67cb1b1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plans',
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('price_rub', sa.Integer(), nullable=False),
    sa.Column('limits', sa.JSON(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('source_policies',
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('material_path', sa.String(length=500), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('basis', sa.Text(), nullable=False),
    sa.Column('responsible', sa.String(length=200), nullable=False),
    sa.Column('allowed_actions', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('attribution_required', sa.Boolean(), nullable=False),
    sa.Column('attribution_text', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('domain', 'material_path', name='uq_source_policy_domain_path')
    )
    op.create_index(op.f('ix_source_policies_domain'), 'source_policies', ['domain'], unique=False)
    op.create_table('users',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_platform_admin', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('workspaces',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('activity_events',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('actor_user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activity_events_workspace_id'), 'activity_events', ['workspace_id'], unique=False)
    op.create_table('exports',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('news_item_ids', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('NOT_SENT', name='exportstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exports_workspace_id'), 'exports', ['workspace_id'], unique=False)
    op.create_table('memberships',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('platform_admin', 'workspace_owner', 'editor', 'viewer', name='role'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'user_id', name='uq_membership_ws_user')
    )
    op.create_index(op.f('ix_memberships_user_id'), 'memberships', ['user_id'], unique=False)
    op.create_index(op.f('ix_memberships_workspace_id'), 'memberships', ['workspace_id'], unique=False)
    op.create_table('news_flows',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('theme', sa.String(length=300), nullable=False),
    sa.Column('schedule_period', sa.String(length=50), nullable=False),
    sa.Column('schedule_time', sa.String(length=5), nullable=False),
    sa.Column('news_limit_per_run', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_news_flows_workspace_id'), 'news_flows', ['workspace_id'], unique=False)
    op.create_table('orders',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'paid', 'canceled', name='orderstatus'), nullable=False),
    sa.Column('amount_rub', sa.Integer(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=200), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index(op.f('ix_orders_workspace_id'), 'orders', ['workspace_id'], unique=False)
    op.create_table('password_reset_tokens',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_password_reset_tokens_token_hash'), 'password_reset_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_password_reset_tokens_user_id'), 'password_reset_tokens', ['user_id'], unique=False)
    op.create_table('sessions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessions_token_hash'), 'sessions', ['token_hash'], unique=True)
    op.create_index(op.f('ix_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    op.create_table('stories',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('story_key', sa.String(length=300), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stories_story_key'), 'stories', ['story_key'], unique=False)
    op.create_index(op.f('ix_stories_workspace_id'), 'stories', ['workspace_id'], unique=False)
    op.create_table('subscriptions',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('current_period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscriptions_workspace_id'), 'subscriptions', ['workspace_id'], unique=False)
    op.create_table('trials',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id')
    )
    op.create_table('payment_events',
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('provider_event_id', sa.String(length=200), nullable=False),
    sa.Column('signature_valid', sa.Boolean(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_event_id', name='uq_payment_event_provider_id')
    )
    op.create_index(op.f('ix_payment_events_order_id'), 'payment_events', ['order_id'], unique=False)
    op.create_table('scan_jobs',
    sa.Column('flow_id', sa.UUID(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=200), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'done', 'failed', name='scanjobstatus'), nullable=False),
    sa.Column('provider_name', sa.String(length=50), nullable=False),
    sa.Column('created_news_ids', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['flow_id'], ['news_flows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('flow_id', 'idempotency_key', name='uq_scan_job_flow_idempotency')
    )
    op.create_index(op.f('ix_scan_jobs_flow_id'), 'scan_jobs', ['flow_id'], unique=False)
    op.create_table('source_sites',
    sa.Column('flow_id', sa.UUID(), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['flow_id'], ['news_flows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('flow_id', 'domain', name='uq_source_site_flow_domain')
    )
    op.create_index(op.f('ix_source_sites_flow_id'), 'source_sites', ['flow_id'], unique=False)
    op.create_table('discoveries',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('scan_job_id', sa.UUID(), nullable=False),
    sa.Column('normalized_url', sa.String(length=2000), nullable=False),
    sa.Column('discovery_domain', sa.String(length=255), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('story_key', sa.String(length=300), nullable=False),
    sa.Column('is_duplicate', sa.Boolean(), nullable=False),
    sa.Column('duplicate_of_news_id', sa.UUID(), nullable=True),
    sa.Column('decision_reason', sa.Text(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['duplicate_of_news_id'], ['news_items.id'], name='fk_discoveries_duplicate_of_news_id', use_alter=True),
    sa.ForeignKeyConstraint(['scan_job_id'], ['scan_jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_discoveries_scan_job_id'), 'discoveries', ['scan_job_id'], unique=False)
    op.create_index(op.f('ix_discoveries_story_key'), 'discoveries', ['story_key'], unique=False)
    op.create_index(op.f('ix_discoveries_workspace_id'), 'discoveries', ['workspace_id'], unique=False)
    op.create_table('news_items',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('flow_id', sa.UUID(), nullable=False),
    sa.Column('story_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('release_mode', sa.Enum('INDEPENDENT_FACT_REPORT', 'ATTRIBUTED_REUSE', name='releasemode'), nullable=False),
    sa.Column('status', sa.Enum('DISCOVERED', 'NEEDS_SOURCE', 'NEEDS_REVIEW', 'DRAFT', 'READY_FOR_REVIEW', 'APPROVED', 'PUBLISHED', 'REJECTED', 'SOURCE_POLICY_REVIEW', 'ACCESS_LIMITED', 'AI_ERROR', 'DUPLICATE', name='newsstatus'), nullable=False),
    sa.Column('discovery_domain', sa.String(length=255), nullable=False),
    sa.Column('discovery_original_fragment', sa.Text(), nullable=False),
    sa.Column('discovery_id', sa.UUID(), nullable=True),
    sa.Column('official_reviewed', sa.Boolean(), nullable=False),
    sa.Column('facts_reviewed', sa.Boolean(), nullable=False),
    sa.Column('attribution_owner', sa.String(length=300), nullable=False),
    sa.Column('attribution_text', sa.Text(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejected_reason', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['discovery_id'], ['discoveries.id'], ),
    sa.ForeignKeyConstraint(['flow_id'], ['news_flows.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_news_items_flow_id'), 'news_items', ['flow_id'], unique=False)
    op.create_index(op.f('ix_news_items_workspace_id'), 'news_items', ['workspace_id'], unique=False)
    op.create_table('editor_reviews',
    sa.Column('news_item_id', sa.UUID(), nullable=False),
    sa.Column('reviewer_user_id', sa.UUID(), nullable=False),
    sa.Column('official_reviewed', sa.Boolean(), nullable=False),
    sa.Column('facts_reviewed', sa.Boolean(), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['news_item_id'], ['news_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewer_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_editor_reviews_news_item_id'), 'editor_reviews', ['news_item_id'], unique=False)
    op.create_table('fact_passports',
    sa.Column('news_item_id', sa.UUID(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('overall_status', sa.Enum('confirmed', 'unknown', 'needs_review', 'contradictory', name='factstatus'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['news_item_id'], ['news_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('news_item_id')
    )
    op.create_table('llm_calls',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('news_item_id', sa.UUID(), nullable=True),
    sa.Column('stage', sa.String(length=50), nullable=False),
    sa.Column('model_uri', sa.String(length=300), nullable=False),
    sa.Column('prompt_version', sa.String(length=50), nullable=False),
    sa.Column('request_id', sa.String(length=100), nullable=False),
    sa.Column('input_hash', sa.String(length=64), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('cost_rub', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['news_item_id'], ['news_items.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_llm_calls_workspace_id'), 'llm_calls', ['workspace_id'], unique=False)
    op.create_table('news_versions',
    sa.Column('news_item_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('edited_by_user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['edited_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['news_item_id'], ['news_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('news_item_id', 'version', name='uq_news_version_item_version')
    )
    op.create_index(op.f('ix_news_versions_news_item_id'), 'news_versions', ['news_item_id'], unique=False)
    op.create_table('official_documents',
    sa.Column('news_item_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('url', sa.String(length=2000), nullable=False),
    sa.Column('requisites', sa.Text(), nullable=False),
    sa.Column('checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('currency_notes', sa.Text(), nullable=False),
    sa.Column('confirmation_limits', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['news_item_id'], ['news_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('news_item_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('official_documents')
    op.drop_index(op.f('ix_news_versions_news_item_id'), table_name='news_versions')
    op.drop_table('news_versions')
    op.drop_index(op.f('ix_llm_calls_workspace_id'), table_name='llm_calls')
    op.drop_table('llm_calls')
    op.drop_table('fact_passports')
    op.drop_index(op.f('ix_editor_reviews_news_item_id'), table_name='editor_reviews')
    op.drop_table('editor_reviews')
    op.drop_index(op.f('ix_news_items_workspace_id'), table_name='news_items')
    op.drop_index(op.f('ix_news_items_flow_id'), table_name='news_items')
    op.drop_table('news_items')
    op.drop_index(op.f('ix_discoveries_workspace_id'), table_name='discoveries')
    op.drop_index(op.f('ix_discoveries_story_key'), table_name='discoveries')
    op.drop_index(op.f('ix_discoveries_scan_job_id'), table_name='discoveries')
    op.drop_table('discoveries')
    op.drop_index(op.f('ix_source_sites_flow_id'), table_name='source_sites')
    op.drop_table('source_sites')
    op.drop_index(op.f('ix_scan_jobs_flow_id'), table_name='scan_jobs')
    op.drop_table('scan_jobs')
    op.drop_index(op.f('ix_payment_events_order_id'), table_name='payment_events')
    op.drop_table('payment_events')
    op.drop_table('trials')
    op.drop_index(op.f('ix_subscriptions_workspace_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_stories_workspace_id'), table_name='stories')
    op.drop_index(op.f('ix_stories_story_key'), table_name='stories')
    op.drop_table('stories')
    op.drop_index(op.f('ix_sessions_user_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_token_hash'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_password_reset_tokens_user_id'), table_name='password_reset_tokens')
    op.drop_index(op.f('ix_password_reset_tokens_token_hash'), table_name='password_reset_tokens')
    op.drop_table('password_reset_tokens')
    op.drop_index(op.f('ix_orders_workspace_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_news_flows_workspace_id'), table_name='news_flows')
    op.drop_table('news_flows')
    op.drop_index(op.f('ix_memberships_workspace_id'), table_name='memberships')
    op.drop_index(op.f('ix_memberships_user_id'), table_name='memberships')
    op.drop_table('memberships')
    op.drop_index(op.f('ix_exports_workspace_id'), table_name='exports')
    op.drop_table('exports')
    op.drop_index(op.f('ix_activity_events_workspace_id'), table_name='activity_events')
    op.drop_table('activity_events')
    op.drop_table('workspaces')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_source_policies_domain'), table_name='source_policies')
    op.drop_table('source_policies')
    op.drop_table('plans')
    # ### end Alembic commands ###
